metadata-files:
  - _brand.yml
 
project:
  type: website
  output-dir: docs

lang: en

website:
  site-url: "https://fruitmeasureapp.udl.cat" # for local test change it to "file:///..."
  favicon: assets/logos/logo.png
  search: true
  title: "FruitMeasureApp"
  open-graph: true
  twitter-card: true
 
format:
  html:
    theme:
      light: [cosmos, assets/styles/theme-light.scss]
    css: 
      - assets/styles/custom.css
    toc: false
    page-layout: full
    highlight-style: github

babelquarto:
  languagelinks: navbar
  languagecodes:
    - name: en
      text: "EN"
    - name: ca
      text: "CA"
    - name: es
      text: "ES"
  mainlanguage: "en"
  languages: ["ca", "es"]

