metadata-files:
  - _brand.yml
 
project:
  type: website
  output-dir: docs/en
 
website:
  favicon: assets/logos/logo.png
  search: true
  title: "FruitMeasureApp"
  open-graph: true
  twitter-card: true
 
  navbar:
    logo: assets/logos/logo.png
    left:
      - href: index.qmd
        text: Home
      - href: general/resources.qmd
        text: Resources
      - href: general/about.qmd
        text: About
      - href: general/credits.qmd
        text: Credits

  page-footer:
    right:
      - "Universitat de Lleida - Institut de Recerca i Tecnologia Agroalimentàries"
 
format:
  html:
    theme:
      light: [cosmos, assets/styles/theme-light.scss]
      #dark:  [cosmos, assets/styles/theme-dark.scss]
    css: assets/styles/custom.css
    toc: false
    page-layout: full
    highlight-style: github

 